query_csv:
  # Nomi delle colonne attese nel CSV di query
  columns:
    - sobject api name
    - soql query
  # Testo del pulsante per caricare il CSV
  prompt: "Carica file query CSV"
  # Filtri di selezione file (estensione .csv)
  filetypes:
    - ["CSV file", "*.csv"]
  separator: ";" #separatore del csv con gli oggetti e le query
