query_csv:
  columns:
  - sobject api name
  - soql query
  prompt: Carica file query CSV
  filetypes:
  - - CSV file
    - '*.csv'
  separator: ;
input_tables: C:/RecordMigration/recordMigrationTool/test.xlsx

