import_settings:
  Contact:
    action: insert
    externalIdField: null
  Account:
    action: insert
    externalIdField: null
  Opportunity:
    action: insert
    externalIdField: null
input_tables: C:/RecordMigration/recordMigrationTool/test2.xlsx
import_order:
- Account
- Opportunity
- Contact
ignore_columns:
- record_id
- to_import
- sf_id
- error
- Id
