input_tables: C:/RecordMigration/recordMigrationTool/test4.xlsx
import_settings:
  Contact:
    action: insert
    externalIdField: null
  Account:
    action: insert
    externalIdField: null
  Opportunity:
    action: insert
    externalIdField: null
import_order:
- Account
- Contact
- Opportunity
ignore_columns:
- record_id
- to_import
- sf_id
- error
- Id
relationships_file: C:/Users/simon/Documents/relationshipTest.csv
query_csv:
  columns:
  - sobject_api
  - soql
  prompt: Carica file query CSV
  filetypes:
  - - CSV file
    - '*.csv'
  separator: ;
ui:
  theme: vista
